export const USER_PHOTO = 'userPhoto/'
export const MODAL_BACKGROUND = 'modalBackground'
export const SUBSCRIBING = 'SUBSCRIBING'
export const SUBSCRIBER = 'SUBSCRIBER'
export const BLOCKANDREJECT = 'BLOCKANDREJECT'
export const REPORT_USER = 'REPORT_USER'
